<?php

namespace Dvsa\Authentication\Ldap;

abstract class AbstractTokenFactory implements TokenFactoryInterface
{
    /**
     * The lifetime of tokens generated by this factory.
     *
     * @var int
     */
    protected $expiresIn = 3600;

    /**
     * Gets an lifetime for tokens created by this factory.
     */
    public function getExpiresIn(): int
    {
        return $this->expiresIn;
    }

    /**
     * Sets an lifetime for tokens created by this factory.
     */
    public function setExpiresIn(int $expiresIn): self
    {
        $this->expiresIn = $expiresIn;

        return $this;
    }

    /**
     * @inheritDoc
     */
    abstract public function make(string $sub, array $claims = []): string;

    /**
     * @inheritDoc
     */
    abstract public function validate(string $token): array;
}
